name: CodeGuru Security POC
on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - "master"

permissions:
  id-token: write
  # for writing security events.
  security-events: write
  # only required for workflows in private repositories
  actions: read
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Respository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_CODEGURU_ROLE_ARN }}
          aws-region: ap-southeast-1
          role-session-name: GitHubActionScript

      - name: CodeGuru Security
        uses: aws-actions/codeguru-security@v1
        with:
          source_path: .
          aws_region: ap-southeast-1
          fail_on_severity: Critical
      - name: Print findings
        run: |
          ls -l
          cat codeguru-security-results.sarif.json

      - name: Upload SARIF file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: codeguru-security-results
          path: codeguru-security-results.sarif.json

      - name: Install dependencies
        run: cd action && npm install

      - name: Comment on PR with scan results
        uses: ./action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull_request_number: ${{ github.event.pull_request.number }}
          sarif_path: codeguru-security-results.sarif.json
          initial_commit_sha: ${{ github.event.pull_request.head.sha }} 
